/********************************** (C) COPYRIGHT *********************************
* File Name          : System.h
* Author             : tech10
* Version            : V1.0
* Date               : 2014/1/1
* Description        : STM 系统函数头文件
**********************************************************************************/

#ifndef __SYSTEM_H
#define __SYSTEM_H

void System_Initialization(void);

#endif

